INSERT INTO gym_exercises (user_id, title, description, body_part)
SELECT u.id, v.title, v.description, v.body_part
FROM (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1) u
CROSS JOIN (VALUES
('Flat Barbell Bench Press', 'Compound push targeting the middle portion of the chest (sternal pectorals) with secondary work for anterior deltoids and triceps.', 'Chest'),
('Flat Barbell Bench Press (Paused)', 'A standard bench press where the barbell is brought down to the lower chest and held in a static, controlled position for 1-2 seconds before pressing back up to lockout. By pausing at the bottom (the most mechanically disadvantaged position), you dissipate elastic energy (the "stretch reflex"). This forces the pectoral muscles and anterior deltoids to recruit more motor units to move the weight from a dead stop, leading to massive gains in raw strength and pressing technique.', 'Chest'),
('Flat Dumbbell Bench Press', 'Compound push targeting the middle portion of the chest (sternal pectorals) with secondary work for anterior deltoids and triceps.', 'Chest'),
('Incline Barbell Bench Press', 'Compound push targeting the upper chest (clavicular pectorals) and front deltoids with triceps involvement.', 'Chest'),
('Incline Dumbbell Bench Press', 'Compound push targeting the upper chest (clavicular pectorals) and front deltoids with triceps involvement.', 'Chest'),
('Flat Dumbbell Flye', 'Isolation movement targeting the middle and outer chest (pectorals) with a deep stretch at the bottom.', 'Chest'),
('Incline Dumbbell Flye', 'Isolation movement targeting the upper chest and front deltoids with emphasis on the clavicular head.', 'Chest'),
('Cable Crossover', 'Isolation movement targeting the inner and middle chest; low pulley emphasizes upper chest, high pulley emphasizes lower chest.', 'Chest'),
('Push-Up', 'Compound push targeting the middle chest, anterior deltoids, and triceps; incline shifts emphasis to lower chest, decline to upper chest.', 'Chest'),
('Dips (Chest Focus)', 'Compound push targeting the lower chest and front deltoids when leaning forward; triceps are heavily involved.', 'Chest'),
('Overhead Barbell Press', 'Compound push targeting the lateral and anterior deltoids (shoulders) with triceps and upper chest involvement.', 'Shoulders'),
('Dumbbell Shoulder Press', 'Compound push targeting the lateral and anterior deltoids with triceps and upper chest as secondary movers.', 'Shoulders'),
('Lateral Raise', 'Isolation movement targeting the lateral deltoids (side of the shoulder).', 'Shoulders'),
('Front Raise', 'Isolation movement targeting the anterior deltoids (front of the shoulder).', 'Shoulders'),
('Reverse Pec Deck / Face Pull', 'Isolation movement targeting the rear deltoids and upper back (rhomboids and traps).', 'Shoulders'),
('Barbell Row', 'Compound pull targeting the middle back (latissimus dorsi, rhomboids) and rear deltoids with biceps involvement.', 'Back'),
('T-Bar Row', 'Compound pull targeting the middle back (lats and rhomboids) and rear deltoids; grip width changes emphasis.', 'Back'),
('Single-Arm Dumbbell Row', 'Compound pull targeting the latissimus dorsi and rhomboids on one side with biceps and rear deltoid involvement.', 'Back'),
('Close-grip Lat Pulldown', 'Adding back density and "thickness.', 'Back'),
('Wide-grip Lat Pulldown', 'Upper lat width and the "V-taper.', 'Back'),
('Pull-Up', 'Compound pull targeting the latissimus dorsi and biceps; underhand grip increases biceps involvement.', 'Back'),
('Chin-Up', 'Compound pull targeting the latissimus dorsi with greater biceps emphasis due to supinated grip.', 'Back'),
('Straight-Arm Pulldown', 'Isolation movement targeting the latissimus dorsi with emphasis on the lower lats.', 'Back'),
('Barbell Curl', 'Isolation movement targeting the biceps brachii (front of the upper arm).', 'Biceps'),
('Dumbbell Curl', 'Isolation movement targeting the biceps brachii; alternating or hammer grip can emphasize different heads.', 'Biceps'),
('Hammer Curl', 'Isolation movement targeting the brachialis and brachioradialis (outer arm and forearm) with biceps involvement.', 'Biceps'),
('Preacher Curl', 'Isolation movement targeting the lower and middle portion of the biceps with reduced swing.', 'Biceps'),
('Cable Curl', 'Isolation movement targeting the biceps brachii with constant tension through the range of motion.', 'Biceps'),
('Close-Grip Bench Press', 'Compound push targeting the triceps (especially lateral and medial heads) with chest and front delt involvement.', 'Triceps'),
('Triceps Pushdown', 'Isolation movement targeting the lateral and medial heads of the triceps.', 'Triceps'),
('Overhead Triceps Extension', 'Isolation movement targeting the long head of the triceps (back of the upper arm).', 'Triceps'),
('Skull Crusher', 'Isolation movement targeting all three heads of the triceps with emphasis on the long head.', 'Triceps'),
('Dips (Triceps Focus)', 'Compound push targeting the triceps (all three heads) when staying upright; chest and delts assist.', 'Triceps'),
('Barbell Back Squat', 'Compound lower-body movement targeting the quadriceps, glutes, and adductors with core and back stabilizers.', 'Legs'),
('Front Squat', 'Compound lower-body movement targeting the quadriceps and upper quad sweep with less lower back load than back squat.', 'Legs'),
('Leg Press', 'Compound push targeting the quadriceps and glutes; foot placement changes emphasis (high = glutes/hamstrings, low = quads).', 'Legs'),
('Leg Extension', 'Isolation movement targeting the quadriceps (front of the thigh), especially the rectus femoris.', 'Legs'),
('Romanian Deadlift', 'Hinge movement targeting the hamstrings (back of the thigh) and glutes with erector spinae involvement.', 'Legs'),
('Leg Curl (Lying)', 'Isolation movement targeting the hamstrings (biceps femoris, semitendinosus, semimembranosus).', 'Legs'),
('Leg Curl (Seated)', 'Isolation movement targeting the hamstrings with emphasis on the lower part of the hamstrings.', 'Legs'),
('Calf Raise (Standing)', 'Isolation movement targeting the gastrocnemius (upper calf).', 'Legs'),
('Calf Raise (Seated)', 'Isolation movement targeting the soleus (lower calf).', 'Legs'),
('Hip Thrust', 'Hip extension targeting the glutes (gluteus maximus) with hamstring and core involvement.', 'Legs'),
('Lunges', 'Compound unilateral movement targeting the quadriceps, glutes, and hamstrings of the leading leg.', 'Legs'),
('Bulgarian Split Squat', 'Unilateral movement targeting the quadriceps and glutes of the front leg with hip flexor stretch on the rear leg.', 'Legs'),
('Barbell Deadlift', 'Compound hinge targeting the entire posterior chain: hamstrings, glutes, erector spinae, and upper back.', 'Back'),
('Plank', 'Isometric hold targeting the core (rectus abdominis, transverse abdominis, and obliques).', 'Core'),
('Cable Crunch', 'Isolation movement targeting the rectus abdominis (upper and middle abs).', 'Core'),
('Hanging Leg Raise', 'Compound movement targeting the lower abdominals and hip flexors with core stability.', 'Core'),
('Russian Twist', 'Rotation movement targeting the obliques (sides of the core) and rectus abdominis.', 'Core'),
('Pec Deck Flye', 'Isolation movement targeting the middle and inner chest (pectorals) with a squeeze at the peak.', 'Chest'),
('Chest Press Machine', 'Compound push targeting the middle chest (sternal pectorals) with fixed path reducing stabilizer demand.', 'Chest'),
('Cable Row', 'Compound pull targeting the middle back (lats and rhomboids) and rear deltoids with biceps.', 'Back'),
('Shrug', 'Isolation movement targeting the upper trapezius (top of the shoulders and neck).', 'Back'),
('Upright Row', 'Compound pull targeting the lateral deltoids and upper trapezius with biceps involvement.', 'Shoulders')
) AS v(title, description, body_part);
