INSERT INTO gym_exercises (user_id, title, description, body_part)
SELECT u.id, v.title, v.description, v.body_part
FROM (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1) u
CROSS JOIN (VALUES
('Flat Bench Press', 'Compound push targeting the middle portion of the chest (sternal pectorals) with secondary work for anterior deltoids and triceps.', 'Chest'),
('Close-Grip Bench Press', 'Compound push targeting the triceps (especially lateral and medial heads) with chest and front delt involvement.', 'Triceps'),
('Incline Bench Press', 'Compound push targeting the upper chest (clavicular pectorals) and front deltoids with triceps involvement.', 'Chest'),
('Chest Press Machine', 'Compound push targeting the middle chest (sternal pectorals) with fixed path reducing stabilizer demand.', 'Chest'),
('Pec Deck Flye', 'Isolation movement targeting the middle and inner chest (pectorals) with a squeeze at the peak.', 'Chest'),
('Cable Crossover', 'Isolation movement targeting the inner and middle chest; low pulley emphasizes upper chest, high pulley emphasizes lower chest.', 'Chest'),
('Push-Up', 'Compound push targeting the middle chest, anterior deltoids, and triceps; incline shifts emphasis to lower chest, decline to upper chest.', 'Chest'),
('Dips (Chest Focus)', 'Compound push targeting the lower chest and front deltoids when leaning forward; triceps are heavily involved.', 'Chest'),
('Overhead Press', 'Compound push targeting the lateral and anterior deltoids (shoulders) with triceps and upper chest involvement.', 'Shoulders'),
('Lateral Raise', 'Isolation movement targeting the lateral deltoids (side of the shoulder).', 'Shoulders'),
('Front Raise', 'Isolation movement targeting the anterior deltoids (front of the shoulder).', 'Shoulders'),
('Reverse Pec Deck / Face Pull', 'Isolation movement targeting the rear deltoids and upper back (rhomboids and traps).', 'Shoulders'),
('Barbell Row', 'Compound pull targeting the middle back (latissimus dorsi, rhomboids) and rear deltoids with biceps involvement.', 'Back'),
('T-Bar Row', 'Compound pull targeting the middle back (lats and rhomboids) and rear deltoids; grip width changes emphasis.', 'Back'),
('Single-Arm Dumbbell Row', 'Compound pull targeting the latissimus dorsi and rhomboids on one side with biceps and rear deltoid involvement.', 'Back'),
('Cable Row', 'Compound pull targeting the middle back (lats and rhomboids) and rear deltoids with biceps.', 'Back'),
('Lat Pulldown', 'Close-grip lat pulldown adds back density and "thickness. Wide-grip lat pulldown targets upper lat width and the "V-taper.', 'Back'),
('Pull-Up', 'Compound pull targeting the latissimus dorsi and biceps; underhand grip increases biceps involvement.', 'Back'),
('Chin-Up', 'Compound pull targeting the latissimus dorsi with greater biceps emphasis due to supinated grip.', 'Back'),
('Straight-Arm Pulldown', 'Isolation movement targeting the latissimus dorsi with emphasis on the lower lats.', 'Back'),
('Barbell Curl', 'Isolation movement targeting the biceps brachii (front of the upper arm).', 'Biceps'),
('Dumbbell Curl', 'Isolation movement targeting the biceps brachii; alternating or hammer grip can emphasize different heads.', 'Biceps'),
('Hammer Curl', 'Isolation movement targeting the brachialis and brachioradialis (outer arm and forearm) with biceps involvement.', 'Biceps'),
('Preacher Curl', 'Isolation movement targeting the lower and middle portion of the biceps with reduced swing.', 'Biceps'),
('Cable Curl', 'Isolation movement targeting the biceps brachii with constant tension through the range of motion.', 'Biceps'),
('Triceps Pushdown', 'Isolation movement targeting the lateral and medial heads of the triceps.', 'Triceps'),
('Overhead Triceps Extension', 'Isolation movement targeting the long head of the triceps (back of the upper arm).', 'Triceps'),
('Dips', 'Compound push targeting the triceps (all three heads) when staying upright; chest and delts assist.', 'Triceps'),
('Back Squat', 'Compound lower-body movement targeting the quadriceps, glutes, and adductors with core and back stabilizers.', 'Legs'),
('Front Squat', 'Compound lower-body movement targeting the quadriceps and upper quad sweep with less lower back load than back squat.', 'Legs'),
('Leg Press', 'Compound push targeting the quadriceps and glutes; foot placement changes emphasis (high = glutes/hamstrings, low = quads).', 'Legs'),
('Leg Extension', 'Isolation movement targeting the quadriceps (front of the thigh), especially the rectus femoris.', 'Legs'),
('Romanian Deadlift', 'Hinge movement targeting the hamstrings (back of the thigh) and glutes with erector spinae involvement.', 'Legs'),
('Leg Curl', 'Isolation movement targeting the hamstrings (biceps femoris, semitendinosus, semimembranosus).', 'Legs'),
('Hip Thrust', 'Hip extension targeting the glutes (gluteus maximus) with hamstring and core involvement.', 'Legs'),
('Deadlift', 'Compound hinge targeting the entire posterior chain: hamstrings, glutes, erector spinae, and upper back.', 'Back'),
('Plank', 'Isometric hold targeting the core (rectus abdominis, transverse abdominis, and obliques).', 'Core'),
('Cable Crunch', 'Isolation movement targeting the rectus abdominis (upper and middle abs).', 'Core'),
('Hanging Leg Raise', 'Compound movement targeting the lower abdominals and hip flexors with core stability.', 'Core'),
('Russian Twist', 'Rotation movement targeting the obliques (sides of the core) and rectus abdominis.', 'Core'),
) AS v(title, description, body_part);
