INSERT INTO recipes (title, description) 
    VALUES ('Classic Margherita Pizza', 'Fresh tomatoes, mozzarella, basil, and a thin crispy crust.'),
    ('Lemon Herb Roasted Chicken', 'Whole chicken with lemon, garlic, and rosemary. Perfect for Sunday dinner.'),
    ('Spaghetti Carbonara', 'Creamy Roman pasta with guanciale, egg, pecorino, and black pepper.'),
    ('Vegetable Stir Fry', 'Quick and colorful stir fry with your favorite vegetables and soy sauce.'),
    ('Chocolate Brownies', 'Fudgy homemade brownies with a crackly top. Best served warm.'),
    ('Greek Salad', 'Cucumbers, tomatoes, olives, feta, and red onion with oregano dressing.'),
    ('Beef Stroganoff', 'Classic Russian beef stew with mushrooms and sour cream. Hearty and comforting.'),
    ('Pad Thai', 'Thai stir-fried noodles with shrimp, tofu, and vegetables. Spicy and flavorful.'),
    ('Chicken Tikka Masala', 'Indian chicken curry with tomatoes, cream, and spices. Rich and aromatic.'),
    ('Fish and Chips', 'Crispy fried fish with crispy fries. A classic British dish.'),
    ('Paella', 'Spanish rice dish with chicken, and vegetables. A classic Spanish dish.'),
    ('Lasagna', 'Italian layered pasta with meat, cheese, and sauce. A classic Italian dish.'),
    ('Ramen', 'Japanese noodle soup with vegetables, meat, and broth. A classic Japanese dish.'),
    ('Sushi', 'Japanese rice with fish, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Tacos', 'Mexican tacos with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Burritos', 'Mexican burritos with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Enchiladas', 'Mexican enchiladas with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Tacos', 'Mexican tacos with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Quesadillas', 'Mexican quesadillas with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Tostadas', 'Mexican tostadas with meat, vegetables, and sauce. A classic Mexican dish.'),
    ('Salmon Sushi', 'Japanese sushi with salmon, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Tuna Sushi', 'Japanese sushi with tuna, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Vegetable Sushi', 'Japanese sushi with vegetables, and soy sauce. A classic Japanese dish.'),
    ('Avocado Sushi', 'Japanese sushi with avocado, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Cucumber Sushi', 'Japanese sushi with cucumber, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Egg Sushi', 'Japanese sushi with egg, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Fish Sushi', 'Japanese sushi with fish, vegetables, and soy sauce. A classic Japanese dish.'),
    ('Shrimp Sushi', 'Japanese sushi with shrimp, vegetables, and soy sauce. A classic Japanese dish.');